# Nama workflow yang akan muncul di tab "Actions" di GitHub
name: Scheduled Beasiswa Scraper

on:
  # Menjalankan workflow secara otomatis sesuai jadwal.
  # Jadwal ini diatur untuk berjalan setiap 6 jam.
  # "0 */6 * * *" artinya: pada menit ke-0, setiap 6 jam.
  # Anda bisa mengubahnya di https://crontab.guru/
  schedule:
    - cron: '0 0 */3 * *'

  # Menambahkan tombol "Run workflow" di tab Actions.
  # Ini sangat berguna untuk melakukan testing tanpa harus menunggu jadwal.
  workflow_dispatch:

jobs:
  # Hanya ada satu 'job' dalam workflow ini, kita beri nama 'scrape'
  scrape:
    # Menggunakan server Ubuntu versi terbaru yang disediakan GitHub
    runs-on: ubuntu-latest

    # Langkah-langkah yang akan dieksekusi secara berurutan
    steps:
      # Langkah 1: Mengunduh kode dari repositori Anda ke server
      - name: Check out repository code
        uses: actions/checkout@v4

      # Langkah 2: Menyiapkan lingkungan Node.js dan cache untuk Yarn
      # Ini penting agar instalasi dependensi lebih cepat di eksekusi berikutnya
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Menggunakan Node.js versi 18
          cache: 'yarn'

      # Langkah 3: Install semua dependensi proyek menggunakan Yarn
      - name: Install dependencies
        run: yarn install --immutable

      # Langkah 4: Install browser yang dibutuhkan oleh Playwright
      # Ini adalah langkah KRUSIAL. Tanpa ini, Playwright akan error.
      # '--with-deps' akan menginstall dependensi sistem yang dibutuhkan di Linux.
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Langkah 5: Menjalankan skrip utama scraper Anda
      - name: Run scraper script
        # Perintah 'yarn scrape' ini diambil dari package.json Anda
        run: yarn scrape
        # Di sinilah kita "menyuntikkan" secret yang sudah kita simpan tadi
        # ke dalam environment variables yang bisa diakses oleh skrip
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
